-- Seed data (SPEC.md). Hand-written migration, applied by `wrangler d1 migrations apply`
-- in filename order. NOT tracked in drizzle's meta/_journal.json (that journal is only
-- read by drizzle-kit generate). NOTE for future schema migrations: drizzle-kit will
-- also number its next file 0001_* — rename the generated file (and its journal tag +
-- meta snapshot prefix) so it sorts after this one.

-- Pipelines ---------------------------------------------------------------
INSERT INTO pipelines (id, name, name_norm, position, created_at, updated_at) VALUES
  (1, 'Export Clients', 'export clients', 1, '2026-06-12T00:00:00.000Z', '2026-06-12T00:00:00.000Z'),
  (2, 'New Leads - Wine', 'new leads - wine', 2, '2026-06-12T00:00:00.000Z', '2026-06-12T00:00:00.000Z');

-- Stages ------------------------------------------------------------------
-- Export Clients: Payment + Waiting for delivery weight 100, all others 50.
INSERT INTO stages (id, pipeline_id, name, name_norm, position, rot_days, forecast_weight, created_at, updated_at) VALUES
  (1, 1, 'Order received', 'order received', 1, 1, 50, '2026-06-12T00:00:00.000Z', '2026-06-12T00:00:00.000Z'),
  (2, 1, 'Proforma Sent', 'proforma sent', 2, 3, 50, '2026-06-12T00:00:00.000Z', '2026-06-12T00:00:00.000Z'),
  (3, 1, 'Proforma confirmed', 'proforma confirmed', 3, 1, 50, '2026-06-12T00:00:00.000Z', '2026-06-12T00:00:00.000Z'),
  (4, 1, 'Payment', 'payment', 4, 3, 100, '2026-06-12T00:00:00.000Z', '2026-06-12T00:00:00.000Z'),
  (5, 1, 'Waiting for delivery', 'waiting for delivery', 5, 5, 100, '2026-06-12T00:00:00.000Z', '2026-06-12T00:00:00.000Z');

-- New Leads - Wine: all weight 50, rot nullable (never rots).
INSERT INTO stages (id, pipeline_id, name, name_norm, position, rot_days, forecast_weight, created_at, updated_at) VALUES
  (6, 2, 'Lead Received', 'lead received', 1, NULL, 50, '2026-06-12T00:00:00.000Z', '2026-06-12T00:00:00.000Z'),
  (7, 2, 'Qualification', 'qualification', 2, NULL, 50, '2026-06-12T00:00:00.000Z', '2026-06-12T00:00:00.000Z'),
  (8, 2, 'Product & Price Presentation', 'product & price presentation', 3, NULL, 50, '2026-06-12T00:00:00.000Z', '2026-06-12T00:00:00.000Z'),
  (9, 2, 'Follow-up / Feedback', 'follow-up / feedback', 4, NULL, 50, '2026-06-12T00:00:00.000Z', '2026-06-12T00:00:00.000Z'),
  (10, 2, 'Negotiation', 'negotiation', 5, NULL, 50, '2026-06-12T00:00:00.000Z', '2026-06-12T00:00:00.000Z'),
  (11, 2, 'Order Confirmation', 'order confirmation', 6, NULL, 50, '2026-06-12T00:00:00.000Z', '2026-06-12T00:00:00.000Z'),
  (12, 2, 'Delivery & Onboarding', 'delivery & onboarding', 7, NULL, 50, '2026-06-12T00:00:00.000Z', '2026-06-12T00:00:00.000Z'),
  (13, 2, 'Post-Sale Follow-Up', 'post-sale follow-up', 8, NULL, 50, '2026-06-12T00:00:00.000Z', '2026-06-12T00:00:00.000Z');

-- FX rates (1 unit of currency = rate_to_eur_micros / 1e6 EUR) -------------
INSERT INTO fx_rates (currency, rate_to_eur_micros, as_of) VALUES
  ('EUR', 1000000, '2026-06-12'),
  ('CHF', 1060000, '2026-06-12'),
  ('GBP', 1170000, '2026-06-12'),
  ('USD', 920000, '2026-06-12');

-- Bootstrap admin (DEV-ONLY password: "changeme-sodimo" — must be changed in
-- production; hash generated by scripts/hash-password.mjs with a fixed salt) --
INSERT INTO users (id, email, name, name_norm, password_hash, role, created_at, updated_at) VALUES
  (1, 'admin@sodimo.eu', 'Sodimo Admin', 'sodimo admin', 'pbkdf2-sha256$600000$c29kaW1vLWRldi1zYWx0$fHhbz+6DIfG0z++jQkUbPmAJ1LsGdZXiAZHsXc07Txg=', 'admin', '2026-06-12T00:00:00.000Z', '2026-06-12T00:00:00.000Z');
